events {}

http {
    upstream users_service {
        server users:8000;
    }

    upstream books_service {
        server books:8000;
    }

    upstream loans_service {
        server loans:8000;
    }

    upstream notifications_service {
        server notifications:8000;
    }

    server {
        listen 80;

        location /usuarios/ {
            proxy_pass http://users_service/;
        }

        location /livros/ {
            proxy_pass http://books_service/;
        }

        location /emprestimos/ {
            proxy_pass http://loans_service/;
        }

        location /notificacoes/ {
            proxy_pass http://notifications_service/;
        }
    }
}
